import type { AppConfig } from '../config.js';
import { formatDate } from './renderConversationMarkdown.js';

export function renderIndex(data: any, config: AppConfig): string {
  const totalMessages = data.threads.reduce((n: number, t: any) => n + t.messages.length, 0);
  const totalMedia = data.threads.reduce((n: number, t: any) => n + t.media.length, 0);
  const latest = data.threads.map((t: any) => t.last_message_at).filter(Boolean).sort().at(-1);
  return `# Instagram DM Markdown Archive\n\nGenerated by ig-dm-md. This archive contains private conversations.\n\n- Total conversations: ${data.threads.length}\n- Total messages: ${totalMessages}\n- Total media items: ${totalMedia}\n- Latest message: ${latest ? formatDate(latest, config, true) : 'n/a'}\n\nSee [conversations.md](conversations.md) and [imports.md](imports.md).\n`;
}
export function renderConversations(data: any, config: AppConfig): string {
  const lines = ['# Conversations', ''];
  for (const cat of ['inbox', 'archived', 'message_requests', 'filtered', 'unknown']) {
    lines.push(`## ${cat.replace('_', ' ')}`, '');
    for (const kind of ['direct', 'group', 'unknown']) {
      const threads = data.threads.filter((t: any) => t.source_category === cat && t.thread_kind === kind);
      if (!threads.length) continue;
      lines.push(`### ${kind}`, '');
      for (const t of threads) lines.push(`- [${t.title}](${t.output_dir}/chat.md) — ${t.participantNames.join(', ')} — ${t.messages.length} messages — ${t.first_message_at ? formatDate(t.first_message_at, config, true) : 'n/a'} to ${t.last_message_at ? formatDate(t.last_message_at, config, true) : 'n/a'}`);
      lines.push('');
    }
  }
  return `${lines.join('\n')}\n`;
}
